### ISSUE TITLE
org.jdbi.examples.v3.Example06Joins fails to pass

### ISSUE THREAD

**Issue by bill-comer** [qualidafial/jdbi-examples#3]
fails with error

java.lang.UnsupportedOperationException: A parameter was not given a name, and parameter name data is not present in the class file, for: public abstract void org.jdbi.examples.v3.Example06Joins$ContactDao.insertPhones(java.util.List,int) :: int arg1

I have tried adding:
@RegisterBeanMapper(Example06Joins.Contact.class)
&
 changing line 45 to
void insertPhones(@BindBean List<Phone> phones,@Bind("contactId") int contactId);
  
But so far have been unsuccessful.

**Comment by qualidafial** [comment]
Actually, I don't think this is a bug in the tests--it depends on your having set the `-parameters` compiler flag.

[Follow these instructions](http://jdbi.github.io/#_automatic_parameter_naming) and see if that addresses your problem.

**Comment by bill-comer** [comment]
You are correct - thanks

**Comment by bill-comer** [comment]
You are correct - thanks
